disabled_rules:
  - line_length
  - function_body_length
  - type_body_length
  - function_parameter_count
  - file_length
  - todo
  - cyclomatic_complexity
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods