disabled_rules:
  - file_length
  - trailing_whitespace
  - line_length 
  - type_name
  - identifier_name
  - type_body_length
  - operator_whitespace
  - function_body_length
  - colon
  - todo
  - multiple_closures_with_trailing_closure
  - unused_optional_binding
  - unused_enumerated
  - cyclomatic_complexity
  - switch_case_alignment
  - shorthand_operator
  - trailing_comma
  - control_statement
  - force_cast
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods