disabled_rules:
  - file_length
  - line_length 
  - type_name
  - identifier_name
  - type_body_length
  - function_body_length
  - todo
  - multiple_closures_with_trailing_closure
  - unused_enumerated
  - cyclomatic_complexity
  - switch_case_alignment
  - shorthand_operator
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods