lane :send_to_appstore do
    run_tests
    capture_ios_screenshots
    frameit
    sigh
    deliver
end

lane :make_screenshots do
  capture_ios_screenshots
  
  frameit(
    white: true
  )
end

lane :refresh_dsyms do
  download_dsyms(
    version: "latest"
  )
  upload_symbols_to_crashlytics(
    api_token: '9ae299de9dd99a73023204eb20b235d7a9cd07c5'
  )
  clean_build_artifacts
end

lane :release do
  build_app(
    scheme: "DigiCloud",
    silent: true,
    clean: true,
    include_bitcode: true
  )
    
  upload_to_app_store(
    force: true
  )
end