# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPhone 5s",
  "iPhone 8",
  "iPhone 8 Plus",
  "iPad Pro (9.7-inch)",
  "iPad Pro (10.5-inch)",
  "iPad Pro (12.9-inch)"
])

languages([
  "en-US",
  # "ro-RO"
])

# The name of the scheme which contains the UI Tests
scheme "Digi Cloud UI Test"

# Where should the resulting screenshots be stored?
# output_directory "./screenshots_snapshot"

clear_previous_screenshots true # remove the '#' to clear all previously generated screenshots before creating new ones
erase_simulator true
reinstall_app true
# concurrent_simulators false

# Choose which project/workspace to use
# project "./Project.xcodeproj"
# workspace "./Project.xcworkspace"

# Arguments to pass to the app on launch. See https://github.com/fastlane/fastlane/tree/master/snapshot#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane snapshot --help
